name: mitness
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_shine: ^0.0.5
  flutter_signin_button: ^1.0.0
  sms_otp_auto_verify: ^1.2.2
  dots_indicator: ^1.2.0
  qr_code_scanner: ^0.3.5
  intro_views_flutter: ^2.9.0
  eva_icons_flutter: ^2.0.0
  carousel_slider: ^2.1.0
  date_format: ^1.0.9
  intl: ^0.15.0
  charts_flutter: ^0.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/images/splash_bg.png
    - assets/images/rectangle.png
    - assets/images/background.png
    - assets/images/qrcode.png
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/mail.png
    - assets/images/mobile.png
    - assets/images/qr.png
    - assets/logo/logo.png
    - assets/logo/loader.gif

